In [1]:
from data_processing import *

In [2]:
translated_filtered, not_translated_filtered = merge_pages()

/Users/markokostiv/ucu/mining_datasets/wiki/data_processing.py:12: RuntimeWarning: Mean of empty slice
  average = data.drop(columns=["page_id", "title"]).apply(lambda x: np.nanmean(x), axis=1)


(141702, 12)
(73566, 12)


In [3]:
translated_filtered.head()

wikidata       title  page_id    len  rev_count  image_links_count  \
0       371         !!!   425480   3953         28                2.0   
1   1622767  !T.O.O.H.!   425157   3031         14                2.0   
2   1075363         '39  2014472   8083         12                4.0   
3   3153272      (ISC)²  2699656  10572         14                1.0   
4   2610124        (if)   550621   2433         17                7.0   

   translations_count  days_old  contributions  outgoing_links_count  \
0                25.0      3399             21                    36   
1                 7.0      3400             13                    20   
2                14.0      1044              4                   148   
3                 5.0        95              2                    13   
4                 2.0      3190             12                    18   

   incoming_links_count  average_views  
0                     7      43.333333  
1                     4      23.000000  
2                   109      51.333333  
3                     2      68.000000  
4                     4      15.666667

In [4]:
not_translated_filtered.head()

wikidata         title  page_id    len  rev_count  image_links_count  \
0   4027682         !ФЕСТ   432740  21769        200               10.0   
1  12061550        !Чидро   590602   2365         12                4.0   
2  30196568   $uicideboy$  2610007   4878          9                2.0   
3     11511           &RQ   156371   4659         22                2.0   
4  25447349  'Cichlasoma'   357578   6104         55                3.0   

   translations_count  days_old  contributions  outgoing_links_count  \
0                 1.0      3383             68                    75   
1                 NaN      3145             10                    13   
2                 6.0       207              6                    14   
3                 2.0      4110             16                   112   
4                 NaN      3598             17                    65   

   incoming_links_count  average_views  
0                    18     501.833333  
1                     3      22.666667  
2                     1     421.500000  
3                    49      46.166667  
4                     6      16.500000

In [5]:
translated_data = translated_filtered.drop(columns = ["wikidata", "page_id"])
not_translated_data = not_translated_filtered.drop(columns = ["wikidata", "page_id"])

In [6]:
translated_data.corr()

len  rev_count  image_links_count  \
len                   1.000000   0.644435           0.428837   
rev_count             0.644435   1.000000           0.450972   
image_links_count     0.428837   0.450972           1.000000   
translations_count    0.270070   0.547634           0.371794   
days_old              0.104303   0.439663           0.044703   
contributions         0.560967   0.910353           0.407156   
outgoing_links_count  0.142372   0.223728           0.143455   
incoming_links_count  0.155882   0.279449           0.163900   
average_views         0.450935   0.621968           0.298734   

                      translations_count  days_old  contributions  \
len                             0.270070  0.104303       0.560967   
rev_count                       0.547634  0.439663       0.910353   
image_links_count               0.371794  0.044703       0.407156   
translations_count              1.000000  0.488521       0.639829   
days_old                        0.488521  1.000000       0.577900   
contributions                   0.639829  0.577900       1.000000   
outgoing_links_count            0.160382  0.216062       0.186291   
incoming_links_count            0.232052  0.117044       0.261683   
average_views                   0.371383  0.212470       0.654638   

                      outgoing_links_count  incoming_links_count  \
len                               0.142372              0.155882   
rev_count                         0.223728              0.279449   
image_links_count                 0.143455              0.163900   
translations_count                0.160382              0.232052   
days_old                          0.216062              0.117044   
contributions                     0.186291              0.261683   
outgoing_links_count              1.000000              0.215438   
incoming_links_count              0.215438              1.000000   
average_views                     0.028007              0.308960   

                      average_views  
len                        0.450935  
rev_count                  0.621968  
image_links_count          0.298734  
translations_count         0.371383  
days_old                   0.212470  
contributions              0.654638  
outgoing_links_count       0.028007  
incoming_links_count       0.308960  
average_views              1.000000

In [7]:
not_translated_data.corr()

len  rev_count  image_links_count  \
len                   1.000000   0.560718           0.253615   
rev_count             0.560718   1.000000           0.270061   
image_links_count     0.253615   0.270061           1.000000   
translations_count    0.099614   0.166016           0.092900   
days_old              0.041610   0.372443           0.072829   
contributions         0.445907   0.844679           0.276713   
outgoing_links_count  0.320793   0.325352           0.383705   
incoming_links_count  0.079337   0.144234           0.112423   
average_views         0.196741   0.387780           0.049438   

                      translations_count  days_old  contributions  \
len                             0.099614  0.041610       0.445907   
rev_count                       0.166016  0.372443       0.844679   
image_links_count               0.092900  0.072829       0.276713   
translations_count              1.000000  0.028962       0.226507   
days_old                        0.028962  1.000000       0.572557   
contributions                   0.226507  0.572557       1.000000   
outgoing_links_count            0.070702  0.084796       0.357756   
incoming_links_count            0.141684  0.058195       0.175227   
average_views                   0.232416  0.108801       0.412664   

                      outgoing_links_count  incoming_links_count  \
len                               0.320793              0.079337   
rev_count                         0.325352              0.144234   
image_links_count                 0.383705              0.112423   
translations_count                0.070702              0.141684   
days_old                          0.084796              0.058195   
contributions                     0.357756              0.175227   
outgoing_links_count              1.000000              0.278069   
incoming_links_count              0.278069              1.000000   
average_views                     0.066740              0.124819   

                      average_views  
len                        0.196741  
rev_count                  0.387780  
image_links_count          0.049438  
translations_count         0.232416  
days_old                   0.108801  
contributions              0.412664  
outgoing_links_count       0.066740  
incoming_links_count       0.124819  
average_views              1.000000

In [8]:
def normalize(data):
    columns = ["rev_count", "image_links_count", "days_old", "contributions", "average_views", "translations_count"]
    for column in columns:
        data[column] = data[column]/data[column].max()

normalize(not_translated_data)
normalize(translated_data)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
translated_data['class'] = 1
not_translated_data['class'] = 0

data = pd.concat([translated_data, not_translated_data])
data.fillna(0, inplace=True)
data.head()

title    len  rev_count  image_links_count  translations_count  \
0         !!!   3953   0.009428           0.005682            0.086505   
1  !T.O.O.H.!   3031   0.004714           0.005682            0.024221   
2         '39   8083   0.004040           0.011364            0.048443   
3      (ISC)²  10572   0.004714           0.002841            0.017301   
4        (if)   2433   0.005724           0.019886            0.006920   

   days_old  contributions  outgoing_links_count  incoming_links_count  \
0  0.642898       0.030129                    36                     7   
1  0.643087       0.018651                    20                     4   
2  0.197465       0.005739                   148                   109   
3  0.017969       0.002869                    13                     2   
4  0.603367       0.017217                    18                     4   

   average_views  class  
0       0.000668      1  
1       0.000355      1  
2       0.000792      1  
3       0.001049      1  
4       0.000242      1

In [11]:
columns_to_drop = ['class', 'title', 'rev_count']

labels = data['class']
dataset = data.drop(columns=columns_to_drop, axis = 1)
dataset.head()

len  image_links_count  translations_count  days_old  contributions  \
0   3953           0.005682            0.086505  0.642898       0.030129   
1   3031           0.005682            0.024221  0.643087       0.018651   
2   8083           0.011364            0.048443  0.197465       0.005739   
3  10572           0.002841            0.017301  0.017969       0.002869   
4   2433           0.019886            0.006920  0.603367       0.017217   

   outgoing_links_count  incoming_links_count  average_views  
0                    36                     7       0.000668  
1                    20                     4       0.000355  
2                   148                   109       0.000792  
3                    13                     2       0.001049  
4                    18                     4       0.000242

In [12]:
X_train, X_test, y_train, y_test = train_test_split(dataset, labels.values, test_size=0.8, random_state=42)

In [13]:
from xgboost import XGBClassifier

In [14]:
xgb_classifier = XGBClassifier()
xgb_classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [15]:
from sklearn.svm import SVC

In [16]:
svm_classifier = SVC()
svm_train = [-1 if y == 0 else 1 for y in y_train]
svm_classifier.fit(X_train, svm_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [17]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

def predict(model, x_test):
    y_pred = model.predict(X_test)
    predictions = [round(value) for value in y_pred]
    return predictions

def evaluate_results(y_test, predictions):
    accuracy = accuracy_score(y_test, predictions)
    matrix = confusion_matrix(y_test, predictions)
    return accuracy, matrix

In [18]:
# 94.17 with contributions
# 94.12 with rev_count
predictions = predict(xgb_classifier, X_test)
accuracy, matrix = evaluate_results(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
print(matrix)

/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Accuracy: 99.08%
[[ 58018    971]
 [   611 112615]]


In [19]:
# 74.74 with contributions
# 74.40 with rev_count
predictions = predict(svm_classifier, X_test)
svm_test = [-1 if y == 0 else 1 for y in y_test]
accuracy, matrix = evaluate_results(svm_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
print(matrix)

Accuracy: 75.83%
[[ 22532  36457]
 [  5175 108051]]


In [20]:
from sklearn.dummy import DummyClassifier
dummy_classifier = DummyClassifier()
dummy_classifier.fit(X_train, y_train)

predictions = predict(dummy_classifier, X_test)
accuracy, matrix = evaluate_results(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
print(matrix)

Accuracy: 55.09%
[[19854 39135]
 [38204 75022]]


In [21]:
# svm_linear_classifier = SVC(kernel = "linear")
# svm_linear_classifier.fit(X_train, svm_train)

In [22]:
# predictions = predict(svm_linear_classifier, X_test)
# svm_test = [-1 if y == 0 else 1 for y in y_test]
# accuracy, matrix = evaluate_results(svm_test, predictions)
# print("Accuracy: %.2f%%" % (accuracy * 100.0))
# print(matrix)

In [23]:
from sklearn.cluster import KMeans

In [24]:
cluster_data = translated_data.drop(columns=columns_to_drop)
cluster_data.fillna(0, inplace=True)

print(cluster_data.head())
k_means = KMeans(n_clusters=1, random_state=0).fit(cluster_data)

     len  image_links_count  translations_count  days_old  contributions  \
0   3953           0.005682            0.086505  0.642898       0.030129   
1   3031           0.005682            0.024221  0.643087       0.018651   
2   8083           0.011364            0.048443  0.197465       0.005739   
3  10572           0.002841            0.017301  0.017969       0.002869   
4   2433           0.019886            0.006920  0.603367       0.017217   

   outgoing_links_count  incoming_links_count  average_views  
0                    36                     7       0.000668  
1                    20                     4       0.000355  
2                   148                   109       0.000792  
3                    13                     2       0.001049  
4                    18                     4       0.000242  


In [25]:
k_means.cluster_centers_

array([[6.35687887e+03, 1.61644243e-02, 9.42832463e-02, 4.72605819e-01,
        1.91532144e-02, 1.68364914e+02, 1.92057056e+02, 1.76173991e-03]])

In [26]:
ranking_data = not_translated_data
ranking_data.fillna(0, inplace=True)
ranking_data.head()

title    len  rev_count  image_links_count  translations_count  \
0         !ФЕСТ  21769   0.280505           0.057471            0.009615   
1        !Чидро   2365   0.016830           0.022989            0.000000   
2   $uicideboy$   4878   0.012623           0.011494            0.057692   
3           &RQ   4659   0.030856           0.011494            0.019231   
4  'Cichlasoma'   6104   0.077139           0.017241            0.000000   

   days_old  contributions  outgoing_links_count  incoming_links_count  \
0  0.640356       0.348718                    75                    18   
1  0.595306       0.051282                    13                     3   
2  0.039182       0.030769                    14                     1   
3  0.777967       0.082051                   112                    49   
4  0.681052       0.087179                    65                     6   

   average_views  class  
0       0.034385      0  
1       0.001553      0  
2       0.028880      0  
3       0.003163      0  
4       0.001131      0

In [27]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances

the_best_translated = k_means.cluster_centers_.reshape(1,-1)

def similarity(features):
    the_best_translated = k_means.cluster_centers_.reshape(1,-1)
    features = features.drop(labels=columns_to_drop, axis=0).values
    features = features.reshape(1,-1)
    similarity = cosine_similarity(features, the_best_translated)
    return similarity

# sim = similarity(np.array([0, 0, 0, 0, 0]))
ranking_with_similarity = ranking_data.copy()
ranking_with_similarity['xgb_ranking'] = xgb_classifier.predict_proba(ranking_data.drop(labels=columns_to_drop, axis=1))[:,[1]]
# ranking_with_similarity['svm_ranking'] = svm_classifier.predict_proba(ranking_data.drop(labels=columns_to_drop, axis=1))[:,[1]]
ranking_with_similarity['cosine_ranking'] = ranking_data.apply(lambda row: similarity(row), axis=1)

In [28]:
ranking_with_similarity.sort_values('cosine_ranking', ascending = False).head()

title   len  rev_count  image_links_count  translations_count  \
33219  Касперівка   637   0.002805           0.000000            0.000000   
20250      Велика   695   0.001403           0.022989            0.067308   
43856      Мизове  2777   0.037868           0.034483            0.038462   
72480    Юнаківка  6545   0.040673           0.045977            0.038462   
22264    Вільшане  2343   0.018233           0.034483            0.028846   

       days_old  contributions  outgoing_links_count  incoming_links_count  \
33219  0.231687       0.005128                    17                    19   
20250  0.048647       0.005128                    18                    21   
43856  0.713231       0.092308                    73                    82   
72480  0.701495       0.107692                   169                   200   
22264  0.701685       0.041026                    62                    69   

       average_views  class  xgb_ranking          cosine_ranking  
33219       0.000799      0     0.004628  [[0.9999998636413592]]  
20250       0.001119      0     0.021382  [[0.9999998247334877]]  
43856       0.004454      0     0.010369  [[0.9999997299045723]]  
72480       0.006212      0     0.031582  [[0.9999997196116003]]  
22264       0.002581      0     0.030731  [[0.9999996838442092]]

In [29]:
# ranking_with_similarity.sort_values('svm_ranking', ascending = False).head()

In [30]:
final_results = ranking_with_similarity.sort_values('xgb_ranking', ascending = False)

In [31]:
final_results = final_results.drop(columns="cosine_ranking")
final_results.to_csv("ranking_final_results.csv", index = False)

In [32]:
final_results.head()

title    len  rev_count  image_links_count  translations_count  \
25900     Даманові  11985   0.009818           0.057471            0.153846   
49653   П'ятирічка   8020   0.032258           0.000000            0.201923   
54274  Підковикові   6685   0.044881           0.034483            0.173077   
60451      Союз-19   6543   0.012623           0.040230            0.086538   
24715   Гребінцеві   7266   0.039271           0.045977            0.221154   

       days_old  contributions  outgoing_links_count  incoming_links_count  \
25900  0.494416       0.015385                   101                    10   
49653  0.741435       0.030769                    46                    33   
54274  0.490062       0.030769                   127                   100   
60451  0.529623       0.035897                   204                   152   
24715  0.831535       0.046154                   107                    18   

       average_views  class  xgb_ranking  
25900       0.002535      0     0.986938  
49653       0.056779      0     0.984154  
54274       0.001736      0     0.973920  
60451       0.002935      0     0.973491  
24715       0.007194      0     0.972054